main: com.celcius.PowerfulPets
version: 2.0
name: PowerfulPets
api-version: 1.16
softdepend: [MMOCore, MiniaturePets, MCPets]
commands:
  powerfulpets:
    description: Comando de origen
    aliases: pp