disabled_worlds:
  - "dungeons"
pets:
  yeti:
    actions:
      onspawn:
        - "potionEffect NIGHT_VISION 1"
        - "attribute vitalidad 1"
      onremove:
        - "potionEffect NIGHT_VISION 1"
        - "attribute vitalidad -1"
